[workspace]
resolver = "2"
members = [
    "crates/cli",
    "crates/ir",
    "crates/codegen",
    "crates/parser",
    "crates/filecheck",
    "crates/triple",
    "crates/macros",
    "crates/interpreter",
    "crates/verifier",
    "crates/sp1",
]
exclude = ["tests/sp1"]

[workspace.package]
edition = "2024"
