pub mod analysis;
pub mod backend;
mod bitset;
pub mod cfg_edit;
pub mod cfg_scc;
pub mod compile;

pub use backend::Backend;
pub use compile::{Compile, EvmCompile, EvmCompiler, OptLevel};
pub mod critical_edge;
pub mod domtree;
pub mod isa;
pub mod liveness;
pub mod loop_analysis;
pub mod machinst;
pub mod module_analysis;
pub mod object;
pub mod optim;
pub mod post_domtree;
pub mod range_analysis;
pub mod stackalloc;
pub mod stackify_edge;
pub mod transform;
