use macros::inst_set;

use crate::inst::*;

#[inst_set(InstKind = "NativeInstKind")]
pub struct NativeInstSet(
    arith::Neg,
    arith::Add,
    arith::Uaddo,
    arith::Uaddsat,
    arith::Saddo,
    arith::Saddsat,
    arith::Mul,
    arith::Sub,
    arith::Usubo,
    arith::Usubsat,
    arith::Ssubo,
    arith::Ssubsat,
    arith::Umulo,
    arith::Umulsat,
    arith::Smulo,
    arith::Smulsat,
    arith::Snego,
    arith::Sdiv,
    arith::Udiv,
    arith::Umod,
    arith::Smod,
    arith::Shl,
    arith::Shr,
    arith::Sar,
    cast::Sext,
    cast::Zext,
    cast::Trunc,
    cast::Bitcast,
    cast::IntToPtr,
    cast::PtrToInt,
    cmp::Lt,
    cmp::Gt,
    cmp::Slt,
    cmp::Sgt,
    cmp::Le,
    cmp::Ge,
    cmp::Sle,
    cmp::Sge,
    cmp::Eq,
    cmp::Ne,
    cmp::IsZero,
    control_flow::Jump,
    control_flow::Br,
    control_flow::Phi,
    control_flow::BrTable,
    control_flow::Call,
    control_flow::Return,
    control_flow::Unreachable,
    data::Mload,
    data::Mstore,
    data::Gep,
    data::GetFunctionPtr,
    data::SymAddr,
    data::SymSize,
    data::Alloca,
    data::ObjAlloc,
    data::ConstRef,
    data::ConstProj,
    data::ConstIndex,
    data::ConstLoad,
    data::ObjProj,
    data::ObjIndex,
    data::ObjLoad,
    data::ObjStore,
    data::ObjInitConst,
    data::EnumMake,
    data::EnumTag,
    data::EnumIsVariant,
    data::EnumAssertVariant,
    data::EnumAssertVariantRef,
    data::EnumExtract,
    data::EnumSetTag,
    data::EnumWriteVariant,
    data::EnumGetTag,
    data::EnumProj,
    data::ObjMaterializeStack,
    data::ObjMaterializeHeap,
    data::MemAllocDynamic,
    data::InsertValue,
    data::ExtractValue,
    logic::Not,
    logic::And,
    logic::Or,
    logic::Xor,
    // EVM arithmetic instructions included for cross-target compilation.
    // On native targets, these are lowered to runtime intrinsic calls
    // by the CraneliftBackend rather than single opcodes.
    evm::EvmAddMod,
    evm::EvmMulMod,
);
