pub mod abi;
mod cleanup;
pub mod combine;
mod enum_lowering;
pub mod legalize;
mod object;
mod object_abi;
mod object_load_store;
mod object_locality;
mod private_abi;
pub mod promotion;
mod reconstruct;
pub mod scalarize;
pub mod shape;

pub use abi::AggregateExpandAbi;
pub use combine::AggregateCombine;
pub use enum_lowering::EnumLowerToProduct;
pub use legalize::{AggregateLowerToMemoryLegalize, assert_aggregate_legalized};
pub use object::ObjectLowerToMemory;
pub use object_abi::ObjectReturnOutParam;
pub use object_load_store::ObjectLoadStore;
pub use scalarize::AggregateScalarize;
