pub mod adce;
pub mod aggregate;
pub mod branch_canonicalize;
pub(crate) mod call_purity;
pub mod cfg_cleanup;
pub mod checked_arith_elim;
pub mod dead_arg;
pub mod dead_func;
pub mod egraph;
pub mod gvn;
pub mod inliner;
pub mod licm;
pub mod load_store;
pub mod loop_strength_reduce;
pub mod multi_result_legalize;
pub mod pipeline;
pub mod sccp;
mod sccp_simplify;
pub(crate) mod signature_rewrite;
mod simplify_expr;

pub use pipeline::{Pass, Pipeline, Step};
